title: Ψηφιακές Εκδόσεις και Νεοελληνικές Σπουδές, Αθήνα, 3-7 Απριλίου 2017hjk
description: Digital Scholarly Editions and Modern Greek Studies | <a href= "http://dixit.uni-koeln.de">DiXiT</a> workshop - Athens, 3-7 April 2017
google_analytics: 
url: https://amsichani.github.io/Digital-Scholarly-EditionsGR-workshop/
twitter_username: amsichani
github_username: amsichani
show_downloads: true
theme: jekyll-theme-minimal

gems:
  - jekyll-mentions
